### ISSUE TITLE
##[error]Docker run failed with exit code 2

### ISSUE THREAD

**Issue by netdesignr** [varunsridharan/action-wp-org-deploy#1]
Hi,
I tried to use this action to deploy a WP plugin but unfortunately, it's failing.

`
A    trunk/lang/etc
A    trunk/.DS_Store
A    trunk/README.md
A    trunk/functions.php
A    trunk/readme.txt
A    trunk/retc to revision 22047XX.
➤ Copying files...
ℹ︎ Using .gitattributes
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
##[error]Docker run failed with exit code 2`

The error is not very helpful and not sure what will it trigger that.

**Comment by varunsridharan** [comment]
@netdesignr It seems that you have not configured it properly
If you could provide your action file content i can check or use the below link for real life example
https://github.com/varunsridharan/wc-product-subtitle/blob/master/.github/workflows/newrelease.yml

you need all the content from that file for this action to run.

<blockquote><img src="https://avatars3.githubusercontent.com/u/1884287?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/varunsridharan/wc-product-subtitle">varunsridharan/wc-product-subtitle</a></strong></div><div>Create Custom Product Subtitle For WooCommerce Products. - varunsridharan/wc-product-subtitle</div></blockquote>

**Comment by varunsridharan** [comment]
But from Line 14th to 17th is optional 
```
      - name: Installing Composer
        uses: pxgamer/composer-action@master
        with:
          command: install --no-dev
```
because it just install your source code's deps

**Comment by netdesignr** [comment]
Hi @varunsridharan 

Thanks a lot for your reply. I've updated the .yml file but unfortunately still no success.
Now is failing on WordPress Plugin Deploy 

`braceexpand    	on
emacs          	off
errexit        	on
errtrace       	off
functrace      	off
hashall        	on
histexpand     	off
history        	off
ignoreeof      	off
interactive-comments	on
keyword        	off
monitor        	off
noclobber      	off
noexec         	off
noglob         	off
nolog          	off
notify         	off
nounset        	off
onecmd         	off
physical       	off
pipefail       	off
posix          	off
privileged     	off
verbose        	off
vi             	off
xtrace         	off
Set the WORDPRESS_USERNAME secret
##[error]Docker run failed with exit code 1
`
`name: New Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Plugin Data
        uses: actions/checkout@v1
      - name: WordPress Plugin Deploy
        uses: varunsridharan/action-wp-org-deploy@master
        with:
          WORDPRESS_PASSWORD: ${{ secrets.WP_PASSWORD }}
          WORDPRESS_USERNAME: ${{ secrets.WP_USERNAME }}
          SLUG: ${{ secrets.WP_SLUG }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}`

**Comment by varunsridharan** [comment]
@netdesignr can you please share your repo url here so i can check the workflow file ?

**Comment by varunsridharan** [comment]
@netdesignr it seems to me that you have not set the 
`WORDPRESS_PASSWORD` && `WORDPRESS_USERNAME` && `WP_SLUG ` values inside your repo's Secrets menu
![image](https://user-images.githubusercontent.com/1884287/70031617-a5aabe00-15d1-11ea-9065-17fc04fc4e30.png)

**Comment by netdesignr** [comment]
https://github.com/netdesignr/remove-admin-toolbar/blob/master/.github/workflows/main.yml
My secrets were named slightly different, however, still failing.

`➤ Copying files...
➤ Removing Exlucded Files From Plugin Source
/entrypoint.sh: line 106: cd: .wordpress-org: No such file or directory
##[error]Docker run failed with exit code 1`

<blockquote><img src="https://avatars1.githubusercontent.com/u/5245264?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/netdesignr/remove-admin-toolbar">netdesignr/remove-admin-toolbar</a></strong></div><div>Remove Admin Toolbar Wordpress Plugin. Contribute to netdesignr/remove-admin-toolbar development by creating an account on GitHub.</div></blockquote>

**Comment by varunsridharan** [comment]
@netdesignr ok i found the issue

Well this action not only updates the source code in WP SVN but also auto uploads its required assets such as

1. Banner
2. Icon
3. Screenshots 

And those needs to be inside a folder named `.wordpress-org` and thats the issue its failing. 

For live example please check here : https://github.com/varunsridharan/wc-product-subtitle
I have a folder named `.wordpress-org`  which contains all the assets for wp.org

<blockquote><img src="https://avatars3.githubusercontent.com/u/1884287?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/varunsridharan/wc-product-subtitle">varunsridharan/wc-product-subtitle</a></strong></div><div>Create Custom Product Subtitle For WooCommerce Products. - varunsridharan/wc-product-subtitle</div></blockquote>

**Comment by netdesignr** [comment]
Right, I will update my repo and try that again. Will come back with the outcome.

Thank you!

**Comment by netdesignr** [comment]
I've definitely added the correct password and username but still gets the error below. Any advice?
svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Commit failed (details follow):

**Comment by varunsridharan** [comment]
@netdesignr it seems that the username / password is incorrect . you may have to renter to ensure that is added properly. also if you want ping me on skype : varunsridharan23 for quicker reply

**Comment by netdesignr** [comment]
Issue resolved by updating `GITHUB_TOKEN: ${{ secrets.TOKEN }}` to GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
